name: Nix

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build Flake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - run: nix build .
      - run: ./result/bin/contrabass --help
